#!/bin/bash

set -e

BASEDIR=$(dirname "$0")
cd $BASEDIR/dist
rm -rf .git
git init
git checkout -b gh-pages
git add *
git commit -m "gh-pages content"
git remote add origin git@github.com:ervanalb/crjson.git
git push --force origin gh-pages -u
